# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/data/AMUbox/Work and studies/Origabot/Code/Motor/motor_test"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/data/AMUbox/Work and studies/Origabot/Code/Motor"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/data/AMUbox/Work and studies/Origabot/Code/Motor/CMakeFiles" "/mnt/data/AMUbox/Work and studies/Origabot/Code/Motor/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/data/AMUbox/Work and studies/Origabot/Code/Motor/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named play_song

# Build rule for target.
play_song: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 play_song
.PHONY : play_song

# fast build rule for target.
play_song/fast:
	$(MAKE) -f src/CMakeFiles/play_song.dir/build.make src/CMakeFiles/play_song.dir/build
.PHONY : play_song/fast

#=============================================================================
# Target rules for targets named buzzer_test

# Build rule for target.
buzzer_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buzzer_test
.PHONY : buzzer_test

# fast build rule for target.
buzzer_test/fast:
	$(MAKE) -f src/CMakeFiles/buzzer_test.dir/build.make src/CMakeFiles/buzzer_test.dir/build
.PHONY : buzzer_test/fast

#=============================================================================
# Target rules for targets named motor_speed_test

# Build rule for target.
motor_speed_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motor_speed_test
.PHONY : motor_speed_test

# fast build rule for target.
motor_speed_test/fast:
	$(MAKE) -f src/CMakeFiles/motor_speed_test.dir/build.make src/CMakeFiles/motor_speed_test.dir/build
.PHONY : motor_speed_test/fast

#=============================================================================
# Target rules for targets named set_id

# Build rule for target.
set_id: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set_id
.PHONY : set_id

# fast build rule for target.
set_id/fast:
	$(MAKE) -f src/CMakeFiles/set_id.dir/build.make src/CMakeFiles/set_id.dir/build
.PHONY : set_id/fast

#=============================================================================
# Target rules for targets named motor_test

# Build rule for target.
motor_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motor_test
.PHONY : motor_test

# fast build rule for target.
motor_test/fast:
	$(MAKE) -f src/CMakeFiles/motor_test.dir/build.make src/CMakeFiles/motor_test.dir/build
.PHONY : motor_test/fast

#=============================================================================
# Target rules for targets named step

# Build rule for target.
step: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 step
.PHONY : step

# fast build rule for target.
step/fast:
	$(MAKE) -f src/CMakeFiles/step.dir/build.make src/CMakeFiles/step.dir/build
.PHONY : step/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... play_song"
	@echo "... buzzer_test"
	@echo "... motor_speed_test"
	@echo "... set_id"
	@echo "... motor_test"
	@echo "... step"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

